# Data Gathering

In [267]:
import numpy as np
import pandas as pd

In [268]:
df = pd.read_csv('/home/calvin/Projects/ML_Movie/data/tmdb_5000_movies.csv')

In [269]:
df.describe()

budget             id   popularity       revenue      runtime  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000   
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859   
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935   
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000   
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000   
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000   
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000   
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000   

       vote_average    vote_count  
count   4803.000000   4803.000000  
mean       6.092172    690.217989  
std        1.194612   1234.585891  
min        0.000000      0.000000  
25%        5.600000     54.000000  
50%        6.200000    235.000000  
75%        6.800000    737.000000  
max       10.000000  13752.000000

In [270]:
df.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

# Feature Processing

Lets take budget, popularity, vote_average to predict revenue 

In [279]:
df_selectFeatures = df[['title','budget', 'popularity', 'vote_average', 'revenue']]
df_selectFeatures.head(5)


title     budget  popularity  \
0                                    Avatar  237000000  150.437577   
1  Pirates of the Caribbean: At World's End  300000000  139.082615   
2                                   Spectre  245000000  107.376788   
3                     The Dark Knight Rises  250000000  112.312950   
4                               John Carter  260000000   43.926995   

   vote_average     revenue  
0           7.2  2787965087  
1           6.9   961000000  
2           6.3   880674609  
3           7.6  1084939099  
4           6.1   284139100

# Pre-Processing

In [280]:
from sklearn.utils import shuffle
df_selectFeatures = shuffle(df_selectFeatures).reset_index(drop=True)

print('Rows Before: {}'.format(df_selectFeatures.shape[0]))
df_selectFeatures = df_selectFeatures[df_selectFeatures.revenue != 0]
df_selectFeatures = df_selectFeatures[df_selectFeatures.budget != 0]
df_selectFeatures = df_selectFeatures[df_selectFeatures.vote_average != 0.0]

print('Rows After: {}'.format(df_selectFeatures.shape[0]))

Rows Before: 4803
Rows After: 3227


# Train & Test Split

In [281]:
from sklearn import model_selection
from sklearn import preprocessing
X = df_selectFeatures[['budget', 'popularity', 'vote_average']]
y = df_selectFeatures[['revenue']]

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y, test_size=0.20, shuffle=False, stratify=None)

In [282]:
#scaler = preprocessing.StandardScaler().fit(X_train)
#X_train_scaled = scaler.transform(X_train)
#y_train_scaled = scaler.transform(X_test)

# Train Models

In [283]:
from sklearn import linear_model

reg_Lasso = linear_model.Lasso(alpha=.7) 
reg_Lasso.fit(X_train, y_train)

Lasso(alpha=0.7, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [284]:
reg_Elastic = linear_model.ElasticNet(random_state=0)
reg_Elastic.fit(X_train, y_train)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

# Test Model

In [285]:
y_pred_Lasso = reg_Lasso.predict(X_test)
y_pred_Elastic = reg_Elastic.predict(X_test)

In [286]:
from sklearn import metrics

print('LASSO \n')
# The coefficients
print('Coefficients: \n', reg.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % metrics.mean_squared_error(y_test, y_pred_Lasso))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % metrics.r2_score(y_test, y_pred_Lasso))

print('\n ELASTIC \n')
# The coefficients
print('Coefficients: \n', reg.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % metrics.mean_squared_error(y_test, y_pred_Elastic))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % metrics.r2_score(y_test, y_pred_Elastic))


LASSO 

Coefficients: 
 [  2.40735790e+00   1.67326659e+06   2.18481316e+07]
Mean squared error: 10048214073099644.00
Variance score: 0.66

 ELASTIC 

Coefficients: 
 [  2.40735790e+00   1.67326659e+06   2.18481316e+07]
Mean squared error: 10228355208044876.00
Variance score: 0.65


In [287]:
LastJedi_predict = [[200000000, 364.077297, 7.9]]
LastJedi_revenue = reg_Lasso.predict(LastJedi_predict)

RogueOne_predict = [[200000000, 46.866663, 7.4]]
RogueOne_revenue = reg_Lasso.predict(RogueOne_predict)

In [288]:
RogueOne_revenue 

array([  5.56622689e+08])

# Ways to improve model

Create a directory popularity feature 
Create an actor popularity feature 
Create a producer popularity feature
Remove/Handle outliers (budget, revenue)
    This created better models ~68% 
Do more searching for errors
Try a different model (several linear regression models available)
Optimize alpha for Lasso using LassoCV
Look at distrubtion of data
Do Cross Validation 